### ISSUE TITLE
Project's `:mvn/repos` should be honored

### ISSUE THREAD

**Issue by lverns** [jpmonettas/clindex#2]
The call to `clojure.tools.deps.alpha/resolve-deps` [here](https://github.com/jpmonettas/clindex/blob/master/src/clindex/scanner.clj#L108) sets the `:mvn/repos` statically, rather than relying on the tooling that t.d.a. provides for determining the repos. This means clindex can't be used on a project with dependencies in a private repository, since t.d.a. throws an ExceptionInfo complaining that it could not find artifact.

**Comment by jpmonettas** [comment]
Thanks for reporting that @lverns, I haven't fully figured out t.d.a repos resolution machinery yet but I'll fix it as soon as I do and find some free time. 
Of course PRs are welcome!

**Comment by jpmonettas** [comment]
This should be fixed by f2d3a264e84a7284d7ae51b8ac1c2a02a25874a9, please reopen if it is still a problem.
